version: "3"
services:
  nginx:
    build: 
      context: .
    image: 
      ${IMAGE_NAME}:${IMAGE_VERSION}
    container_name:
        nginx
    ports:
      - "8888:80"
    volumes:
        - ${CONF_DIR}:C:\nginx\conf

#
# EOF (2022/04/29)
#